package no.npolar.data.api;

import org.opencms.i18n.A_CmsMessageBundle;
import org.opencms.i18n.I_CmsMessageBundle;

/**
 * Convenience class to access the localized messages of this OpenCms package.
 * 
 * @author Paul-Inge Flakstad, Norwegian Polar Institute <flakstad at npolar.no>
 */
public class Messages extends A_CmsMessageBundle {
    /** Message used for e-mail */
    public static final String MSG_DATA_CENTRE_UNAVAILABLE_EMAIL_BODY_3 = "MSG_DATA_CENTRE_UNAVAILABLE_EMAIL_BODY_3"; //The page at {0} is having problems connecting to the data centre.\n\nPlease look into this.\n\nThis notification was generated because the data centre is down, frozen/hanging, or did not respond with the expected response code \"200 OK\".\n\nGenerated by OpenCms: {1} - No further notifications will be sent for the next {2} hour(s).

    /** Name of the used resource bundle. */
    private static final String BUNDLE_NAME = "no.npolar.workplace.tools.messages";

    /** Static instance member. */
    private static final I_CmsMessageBundle INSTANCE = new Messages();
    
    /**
     * Hides the public constructor for this utility class.<p>
     */
    private Messages() {
        // hide the constructor
    }

    /**
     * Returns an instance of this localized message accessor.<p>
     * 
     * @return an instance of this localized message accessor.
     */
    public static I_CmsMessageBundle get() {
        return INSTANCE;
    }

    /**
     * Returns the bundle name for this OpenCms package.<p>
     * 
     * @return the bundle name for this OpenCms package
     */
    @Override
    public String getBundleName() {
        return BUNDLE_NAME;
    }
}
